# Generated by Django 2.1.7 on 2019-03-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mail_id',
            field=models.CharField(default='default@gmail.com', max_length=20),
        ),
    ]
