# Generated by Django 2.1.7 on 2019-03-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0002_question_mail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mail_id',
            field=models.CharField(default='default@gmail.com', max_length=45),
        ),
    ]
